export const EXPERTS_DATA = [
  {
    id: "meera-iyer",
    name: "Dr. Meera Iyer",
    lastName: "Iyer",
    specialty: "DIABETES & BLOOD SUGAR",
    credential: "Registered Dietitian · RD, MSc",
    description: "Helps manage HbA1c through everyday South Indian meals",
    bullets: [
      "Reducing HbA1c through diet alone",
      "South Indian meal plans for T2D",
    ],
    rating: 4.9,
    sessions: 312,
    location: "Chennai",
    languages: "Tamil, English, Hindi",
    points: 200,
    accentColor: "#2542A5",
    badgeBg: "bg-[#2542A5]",
    borderClass: "border-[#2542A5]",
    textAccent: "text-[#2542A5]",
    btnBg: "bg-[#2542A5] hover:bg-[#1d3587]",
    category: "blood-sugar",
    region: "south",
    avatar: "/images/experts/meera_iyer.jpg",
    about:
      "Dr. Meera Iyer specializes in metabolic health, glycemic control, and sustainable diabetes reversal using traditional South Indian staple foods. With over 12 years of clinical dietetics practice, she works closely with individuals with prediabetes and Type 2 diabetes to lower HbA1c levels without giving up idlis, dosas, or regional comfort foods.",
    qualifications: [
      "MSc Clinical Nutrition & Dietetics, Madras Medical College",
      "Registered Dietitian (RD) – Indian Dietetic Association (IDA)",
      "Certified Diabetes Educator (CDE)",
      "Advanced Glycemic Index & Insulin Response Practitioner",
    ],
    helpTopics: [
      "Lowering HbA1c through everyday South Indian meals",
      "Millet & low-GI grain transition without digestive distress",
      "Dosa, Idli & rice portioning strategies for glucose control",
      "Diabetic-friendly festive and wedding season meal prep",
      "Continuous Glucose Monitor (CGM) data interpretation",
    ],
    testimonials: [
      {
        stars: 5,
        quote: "Dr. Meera helped me bring my HbA1c down from 8.2 to 6.4 in 4 months without cutting out sambar or rasam. Life-changing!",
        author: "Karthik R.",
        city: "Chennai",
      },
      {
        stars: 5,
        quote: "Very practical advice for South Indian households. My whole family is eating better now.",
        author: "Lakshmi S.",
        city: "Bengaluru",
      },
    ],
  },
  {
    id: "rohit-malhotra",
    name: "Rohit Malhotra",
    lastName: "Malhotra",
    specialty: "FITNESS & MUSCLE GAIN",
    credential: "Sports & Performance Nutritionist",
    description: "Designs high-protein Indian meal plans for serious training",
    bullets: [
      "High-protein Indian meal builds",
      "Pre/post-workout meal timing",
    ],
    rating: 4.8,
    sessions: 224,
    location: "Delhi",
    languages: "Hindi, English, Punjabi",
    points: 150,
    accentColor: "#1B7042",
    badgeBg: "bg-[#1B7042]",
    borderClass: "border-[#1B7042]",
    textAccent: "text-[#1B7042]",
    btnBg: "bg-[#1B7042] hover:bg-[#145a34]",
    category: "fitness",
    region: "north",
    avatar: "/images/experts/rohit_malhotra.jpg",
    about:
      "Rohit works with amateur athletes, gym-goers, and competitive runners to optimise their nutrition without abandoning Indian food. Formerly a strength & conditioning coach, he pivoted to nutrition after seeing how poorly most Western fitness advice translated to authentic Indian eating habits.",
    qualifications: [
      "BSc Sports Science, Delhi University",
      "ISSN Certified Sports Nutritionist",
      "Certified Strength & Conditioning Specialist (CSCS)",
      "High-Performance Athletic Meal Design Specialist",
    ],
    helpTopics: [
      "High-protein Indian meal builds",
      "Pre/post-workout meal timing",
      "Vegetarian muscle gain strategies",
      "Creatine & supplement guidance",
      "Competition-season cutting diets",
    ],
    testimonials: [
      {
        stars: 5,
        quote: "Built me a dal-paneer-based bulking plan that actually worked. 8 kg muscle in 5 months.",
        author: "Arjun M.",
        city: "Delhi",
      },
      {
        stars: 4,
        quote: "Rohit understands that not everyone wants to eat chicken 6 times a day. Excellent for vegetarians.",
        author: "Sonia T.",
        city: "Gurgaon",
      },
    ],
  },
  {
    id: "fatima-khan",
    name: "Dr. Fatima Khan",
    lastName: "Khan",
    specialty: "WEIGHT MANAGEMENT",
    credential: "Clinical Nutritionist · PhD",
    description: "Evidence-based weight loss through sustainable Indian eating",
    bullets: [
      "Sustainable fat loss without crash dieting",
      "Biryani & heavy meals without guilt",
    ],
    rating: 4.9,
    sessions: 445,
    location: "Hyderabad",
    languages: "Urdu, Hindi, English, Telugu",
    points: 250,
    accentColor: "#E0187A",
    badgeBg: "bg-[#E0187A]",
    borderClass: "border-[#E0187A]",
    textAccent: "text-[#E0187A]",
    btnBg: "bg-[#E0187A] hover:bg-[#c41267]",
    category: "weight",
    region: "south",
    avatar: "/images/experts/fatima_khan.jpg",
    about:
      "Dr. Fatima Khan focuses on sustainable, non-restrictive fat loss that honors Indian culinary heritage. She rejects crash diets in favor of bio-individual energy balance, metabolic flexibility, and smart swap frameworks for rich Mughlai and Hyderabadi dishes.",
    qualifications: [
      "PhD in Human Nutrition, Osmania University",
      "Registered Clinical Dietitian (RD)",
      "Member, World Obesity Federation",
      "Certified Bariatric & Metabolic Health Consultant",
    ],
    helpTopics: [
      "Sustainable fat loss without crash dieting",
      "Biryani & heavy festive meals without guilt",
      "Post-pregnancy weight management",
      "Overcoming weight-loss plateaus",
      "Binge-eating and emotional relationship with food",
    ],
    testimonials: [
      {
        stars: 5,
        quote: "Lost 14 kg over 6 months without feeling hungry once. I still eat biryani on Sundays!",
        author: "Zainab K.",
        city: "Hyderabad",
      },
      {
        stars: 5,
        quote: "Her swap techniques made home cooking so much easier and healthier.",
        author: "Aditya V.",
        city: "Pune",
      },
    ],
  },
  {
    id: "priya-nair",
    name: "Priya Nair",
    lastName: "Nair",
    specialty: "HOLISTIC & GUT HEALTH",
    credential: "Ayurvedic Nutrition Coach",
    description: "Blends Ayurvedic principles with modern nutritional science",
    bullets: [
      "Dosha-based eating for your body type",
      "IBS and gut inflammation through diet",
    ],
    rating: 4.7,
    sessions: 178,
    location: "Kochi",
    languages: "Malayalam, English, Hindi",
    points: 100,
    accentColor: "#CB5638",
    badgeBg: "bg-[#CB5638]",
    borderClass: "border-[#CB5638]",
    textAccent: "text-[#CB5638]",
    btnBg: "bg-[#CB5638] hover:bg-[#b0462b]",
    category: "gut-health",
    region: "south",
    avatar: "/images/experts/priya_nair.jpg",
    about:
      "Priya bridges the 5,000-year wisdom of Ayurveda with contemporary nutritional research. She designs tailored dietary protocols based on individual Prakriti/Dosha imbalances, digestive fire (Agni), and seasonal Ritucharya rhythms.",
    qualifications: [
      "BAMS (Ayurveda), Kerala University of Health Sciences",
      "Postgraduate Diploma in Holistic Nutrition",
      "Certified Gut Microbiome & Digestive Health Coach",
      "Member, National Ayurvedic Medical Association",
    ],
    helpTopics: [
      "Dosha-based eating for your body type",
      "IBS and gut inflammation through diet",
      "Ayurvedic herbs & spices for daily digestion",
      "Seasonal eating transitions (Ritucharya)",
      "Chronic bloating and acidity management",
    ],
    testimonials: [
      {
        stars: 5,
        quote: "Cured my 3-year bloating issue in just 6 weeks with simple kitchen spice adjustments.",
        author: "Ananya B.",
        city: "Kochi",
      },
      {
        stars: 4,
        quote: "The combination of modern macros and Ayurvedic dosha principles works wonders.",
        author: "Rahul D.",
        city: "Mumbai",
      },
    ],
  },
  {
    id: "arjun-sharma",
    name: "Arjun Sharma",
    lastName: "Sharma",
    specialty: "VEGAN TRANSITION & FITNESS",
    credential: "Plant-Based Food Coach",
    description: "Makes vegan eating practical and high-protein in an Indian kitchen",
    bullets: [
      "Full vegan transition plans",
      "Getting 100g+ protein on a plant diet",
    ],
    rating: 4.8,
    sessions: 203,
    location: "Mumbai",
    languages: "Hindi, English, Marathi",
    points: 120,
    accentColor: "#1B7042",
    badgeBg: "bg-[#1B7042]",
    borderClass: "border-[#1B7042]",
    textAccent: "text-[#1B7042]",
    btnBg: "bg-[#1B7042] hover:bg-[#145a34]",
    category: "fitness",
    region: "west",
    avatar: "/images/experts/arjun_sharma.jpg",
    about:
      "Arjun makes vegan eating achievable, affordable, and rich in protein within authentic Indian households. He guides clients through transitioning away from dairy without losing paneer, dahi, or ghee textures in everyday recipes.",
    qualifications: [
      "Certified Plant-Based Nutritionist (eCornell)",
      "Precision Nutrition Level 2 Master Coach",
      "BSc Food Science & Technology, Mumbai University",
    ],
    helpTopics: [
      "Full vegan transition plans for Indian homes",
      "Getting 100g+ protein on a 100% plant diet",
      "Plant-based dairy swaps for chai, curd & paneer",
      "Micronutrient supplementation (B12, D3, Iron)",
      "Vegan meal planning for dining out & travel",
    ],
    testimonials: [
      {
        stars: 5,
        quote: "Swapped dairy effortlessly. Arjun's homemade peanut-curd recipe is unbelievable!",
        author: "Neha P.",
        city: "Mumbai",
      },
      {
        stars: 5,
        quote: "Hitting 120g protein daily on a purely vegan Indian diet now.",
        author: "Varun K.",
        city: "Ahmedabad",
      },
    ],
  },
  {
    id: "sunita-rao",
    name: "Dr. Sunita Rao",
    lastName: "Rao",
    specialty: "FAMILY & CHILD NUTRITION",
    credential: "Paediatric & Family Nutritionist",
    description: "Practical nutrition for Indian families with young children",
    bullets: [
      "Feeding fussy eaters with Indian foods",
      "School tiffin planning with good nutrition",
    ],
    rating: 4.9,
    sessions: 389,
    location: "Bengaluru",
    languages: "Kannada, English, Telugu, Hindi",
    points: 180,
    accentColor: "#2542A5",
    badgeBg: "bg-[#2542A5]",
    borderClass: "border-[#2542A5]",
    textAccent: "text-[#2542A5]",
    btnBg: "bg-[#2542A5] hover:bg-[#1d3587]",
    category: "budget",
    region: "south",
    avatar: "/images/experts/sunita_rao.jpg",
    about:
      "Dr. Sunita Rao helps parents navigate childhood nutrition, weaning, adolescent growth spurts, and fussy eating behaviors using nutrient-dense Indian ingredients without daily mealtime battles.",
    qualifications: [
      "MD Paediatric Nutrition, NIMHANS / Rajiv Gandhi Health Sciences",
      "Member, Indian Academy of Paediatrics (IAP)",
      "Certified Child Growth & Development Specialist",
    ],
    helpTopics: [
      "Feeding fussy eaters with familiar Indian foods",
      "School tiffin planning with balanced macros",
      "First foods & weaning guides for toddlers",
      "Childhood allergy and lactose sensitivity plans",
      "Building positive food relationships at home",
    ],
    testimonials: [
      {
        stars: 5,
        quote: "My 6-year-old finally eats greens thanks to Dr. Sunita's creative tiffin ideas.",
        author: "Meenakshi G.",
        city: "Bengaluru",
      },
      {
        stars: 5,
        quote: "Gentle, scientific, and deeply empathetic approach to parenting and food.",
        author: "Deepak N.",
        city: "Mysuru",
      },
    ],
  },
  {
    id: "vikram-bose",
    name: "Vikram Bose",
    lastName: "Bose",
    specialty: "AFFORDABLE HEALTHY EATING",
    credential: "Budget Nutrition Specialist",
    description: "Maximises nutrition on India's tightest food budgets",
    bullets: [
      "High-nutrition meal plans under ₹100/day",
      "Seasonal vegetable nutrition",
    ],
    rating: 4.6,
    sessions: 156,
    location: "Kolkata",
    languages: "Bengali, Hindi, English",
    points: 80,
    accentColor: "#F5AE38",
    badgeBg: "bg-[#F5AE38]",
    borderClass: "border-[#F5AE38]",
    textAccent: "text-[#D2932B]",
    btnBg: "bg-[#F5AE38] hover:bg-[#e09b25]",
    category: "budget",
    region: "east",
    avatar: "/images/experts/vikram_bose.jpg",
    about:
      "Vikram proves that optimal nutrition is not a luxury. He designs high-protein, micronutrient-dense meal plans utilizing seasonal mandi produce, bulk pulse sourcing, and simple kitchen staples under strict budget targets.",
    qualifications: [
      "MSc Food Economics, Calcutta University",
      "Certified Public Health Nutritionist",
      "Community Meal Planning Consultant",
    ],
    helpTopics: [
      "High-nutrition meal plans under ₹100/day",
      "Seasonal local vegetable & greens utilization",
      "Bulk pulse & grain buying guides for families",
      "Budget-friendly protein optimization",
      "Zero-waste Indian meal prep and storage",
    ],
    testimonials: [
      {
        stars: 5,
        quote: "Halved our monthly grocery bill while actually increasing our daily protein intake.",
        author: "Sourav M.",
        city: "Kolkata",
      },
      {
        stars: 4,
        quote: "Incredible knowledge of local seasonal produce and Indian markets.",
        author: "Tanmoy B.",
        city: "Howrah",
      },
    ],
  },
  {
    id: "ananya-patel",
    name: "Dr. Ananya Patel",
    lastName: "Patel",
    specialty: "GUT HEALTH & IMMUNITY",
    credential: "Gut Health & Microbiome Specialist",
    description: "Rewires gut health through fermented Indian foods and probiotics",
    bullets: [
      "IBD, IBS and leaky gut through diet",
      "Indian fermented foods as probiotics",
    ],
    rating: 4.8,
    sessions: 267,
    location: "Pune",
    languages: "Gujarati, Hindi, English, Marathi",
    points: 220,
    accentColor: "#CB5638",
    badgeBg: "bg-[#CB5638]",
    borderClass: "border-[#CB5638]",
    textAccent: "text-[#CB5638]",
    btnBg: "bg-[#CB5638] hover:bg-[#b0462b]",
    category: "gut-health",
    region: "west",
    avatar: "/images/experts/ananya_patel.jpg",
    about:
      "Dr. Ananya Patel is a microbiome researcher who harnesses traditional Indian fermented foods—like kanji, handvo, fermented rice, and buttermilk—to rebuild diverse gut flora, alleviate chronic inflammation, and boost immune resilience.",
    qualifications: [
      "PhD Microbiome Sciences & Nutrition, Pune University",
      "Fellow, International Society for Microbiota",
      "Registered Clinical Dietitian (RD)",
    ],
    helpTopics: [
      "IBD, IBS and leaky gut protocols through diet",
      "Traditional Indian fermented foods as probiotics",
      "Post-antibiotic gut microbiome restoration",
      "Food intolerance and elimination diet coaching",
      "Gut-brain axis, anxiety & digestion connections",
    ],
    testimonials: [
      {
        stars: 5,
        quote: "Her traditional fermented food protocol solved digestive struggles I had for 7 years.",
        author: "Pooja J.",
        city: "Ahmedabad",
      },
      {
        stars: 5,
        quote: "Dr. Ananya's guidance on fermented kanji and prebiotic foods is top notch.",
        author: "Nikhil S.",
        city: "Pune",
      },
    ],
  },
];

export const GOAL_FILTERS = [
  { id: "all", label: "ALL GOALS" },
  { id: "fitness", label: "FITNESS" },
  { id: "weight", label: "WEIGHT" },
  { id: "blood-sugar", label: "BLOOD SUGAR" },
  { id: "budget", label: "BUDGET" },
];

export const REGION_FILTERS = [
  { id: "all", label: "All India" },
  { id: "north", label: "North" },
  { id: "south", label: "South" },
  { id: "west", label: "West" },
  { id: "east", label: "East" },
];

export const MY_REQUESTS = [
  {
    id: "req-1",
    expertName: "Dr. Meera Iyer",
    expertAvatar: "/images/experts/meera_iyer.jpg",
    status: "ACCEPTED",
    statusColor: "text-[#1B7042] bg-[#1B7042]/10 border-[#1B7042]/30",
    borderAccent: "border-l-4 border-l-[#1B7042]",
    message: "I have Type 2 diabetes and want a South Indian meal plan to lower my...",
    meta: "Sent 2 days ago · via WhatsApp",
    points: 200,
  },
  {
    id: "req-2",
    expertName: "Vikram Bose",
    expertAvatar: "/images/experts/vikram_bose.jpg",
    status: "DECLINED",
    statusColor: "text-[#CB5638] bg-[#CB5638]/10 border-[#CB5638]/30",
    borderAccent: "border-l-4 border-l-[#CB5638]",
    message: "Looking for a high-protein budget meal plan for my family of three, sp...",
    meta: "Sent 5 days ago · via video call",
    points: 80,
  },
];
